export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';
export const ADD_USER = 'ADD_USER';

export const SEARCH_USERS = 'SEARCH_USERS';
export const SEARCH_USERS_END = 'SEARCH_USERS_END';

export const GET_UESRS_INFO = 'GET_UESRS_INFO';
export const GET_UESRS_INFO_SUCCESS = 'GET_UESRS_INFO_SUCCESS';

export const SEND_EMAIL = 'SEND_EMAIL';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';

export const SET_SEARCH_DATA = 'SET_SEARCH_DATA';
export const UPDATE_UESR = 'UPDATE_UESR';